[project]
name = "robot-sensor-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mardhav-2008", email = "mardhavrayapati81@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "sympy>=1.14.0",
]

[project.scripts]
robot-sensor-analysis = "robot_sensor_analysis:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
